title: How Sample?
description: Fianl Project for CTP431
show_downloads: false
project_link: https://jjong84.github.io/HowSample
github_link: https://github.com/JJong84/HowSample
colab_link: https://colab.research.google.com/drive/1B5A8QaD72YDuE8PHFNWZ3uCfZrzJbSHJ?usp=sharing
repository_url: https://github.com/JJong84/CTP431-Final
theme: jekyll-theme-cayman
